services:
  ivr-app:
    container_name: ivr-interactivo
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "4005:4005"
    env_file:
      - ./Backend/.env.production
    restart: always
